services:
  classinsight:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: classinsight
    ports:
      - "8082:8080"
    networks:
      - classinsight-network
    restart: unless-stopped
    depends_on:
      - classinsight-postgres
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: "jdbc:postgresql://classinsight-postgres:5432/classinsight_db"
      SPRING_DATASOURCE_USERNAME: "classinsight_user"
      SPRING_DATASOURCE_PASSWORD: "classinsight_pass"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    volumes:
      - classinsight-logs:/var/log/classinsight

  classinsight-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: classinsight_db
      POSTGRES_USER: classinsight_user
      POSTGRES_PASSWORD: classinsight_pass
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - classinsight-network
    restart: unless-stopped

volumes:
  user_postgres_data:
  classinsight-logs:

networks:
  classinsight-network:
    driver: bridge
