services:
  classinsight:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: classinsight
    ports:
      - "8082:8080"
    networks:
      - classinsight-network
    restart: unless-stopped
    depends_on:
      - classinsight-postgres
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}

    volumes:
      - classinsight-logs:/var/log/classinsight

  classinsight-postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - classinsight-network
    restart: unless-stopped

volumes:
  user_postgres_data:
  classinsight-logs:

networks:
  classinsight-network:
    driver: bridge
