services:
  classinsight:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: classinsight
    ports:
      - "8080:8082"
    networks:
      - classinsight-network
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}

    volumes:
      - classinsight-logs:/var/log/classinsight

volumes:
  classinsight-logs:

networks:
  classinsight-network:
    driver: bridge
