server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://user-postgres:5432/classinsight_db
    driver-class-name: org.postgresql.Driver
    username: classinsight_user
    password: classinsight_pass
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: ERROR
    br.com.edu.classinsight: INFO
  file:
    name: /var/log/classinsight/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"