server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/classinsight_db
    driver-class-name: org.postgresql.Driver
    username: classinsight_user
    password: classinsight_pass
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
